- globals.json
fixes https://github.com/eslint/eslint/issues/1737
> Mocha globals missing 'xdescribe' and 'xit'

- globals.json
Spec: https://html.spec.whatwg.org/multipage/comms.html#the-eventsource-interface
Fixes #38.
> Add `EventSource` to browser globals

- globals.json
See https://developer.mozilla.org/en-US/docs/Web/API/ImageData.
> Add ImageData to browser globals

- globals.json
As specified at http://facebook.github.io/jest/docs/api.html#globally-injected-variables
> Add Jest globals

- globals.json
See https://github.com/shelljs/shelljs#lnoptions-source-dest
> Add shelljs.ln

- globals.json
More information at:
- https://url.spec.whatwg.org/#urlsearchparams
- https://developer.mozilla.org/en-US/docs/Web/API/URLSearchParams
> Add URLSearchParams browser global

- globals.json
https://atmospherejs.com/meteor/service-configuration
> Add `ServiceConfiguration` for Meteor

- globals.json
Adds `IntersectionObserver` and `IntersectionObserverEntry` constructors:
https://wicg.github.io/IntersectionObserver/
> Add new IntersectionObserver browser globals

- globals.json
Add `check` and `gen`, which are new globals in `jest`. Test passes.
> Add 'check' and 'gen' to 'jest'.

- globals.json
We are adding this global to Jest, sorry about that :)
> Add "test" global for Jest

- globals.json
Here is the specification: https://html.spec.whatwg.org/multipage/webappapis.html#promiserejectionevent
> Add browser "PromiseRejectionEvent" global

- globals.json
Related to #98 but doesn't remove any globals
> Add `fdescribe` to Jest

- globals.json
https://developer.mozilla.org/en-US/docs/Web/API/WindowOrWorkerGlobalScope/createImageBitmap
> Add createImageBitmap to browser

- globals.json
[OffscreenCanvas on MDN](https://developer.mozilla.org/en-US/docs/Web/API/OffscreenCanvas)
> Add OffscreenCanvas to browser globals

- globals.json
Ref: https://github.com/emberjs/ember-test-helpers/pull/308
> Add findAll to embertest

- .travis.yml
- index.d.ts
- index.test-d.ts
- package.json
Waiting for https://github.com/sindresorhus/type-fest/pull/34.
> Add TypeScript definition and require Node.js 8

- get-browser-globals.js
Small PR to rename this variable, since I noticed it. No user-facing changes.
> Use better language for a variable

- globals.json
https://html.spec.whatwg.org/multipage/canvas.html#offscreencanvasrenderingcontext2d
> Add `OffscreenCanvasRenderingContext2D` to `browser` environment

- globals.json
> Add `DOMRectList` to browser environment

- globals.json
Add `GM_addElement` (experimental CSP bypass).
Refs: Tampermonkey/tampermonkey#881
> Add `GM_addElement` to `greasemonkey`

- globals.json
MDN: https://developer.mozilla.org/en-US/docs/Web/API/TransformStream
Spec: https://streams.spec.whatwg.org/#ts-class
> Add TransformStream for browser

- globals.json
Ref: https://developer.mozilla.org/en-US/docs/Web/API/ClipboardItem
> Add `ClipboardItem` to browser

- globals.json
Add [**`NavigatorUAData`**](https://developer.mozilla.org/en-US/docs/Web/API/NavigatorUAData) (_Navigator User Agent Data_) interface to browser.
> Add `NavigatorUAData` to browser

- .github/workflows/update.yml
Same as https://github.com/sindresorhus/get-east-asian-width/pull/7
> Auto create pull request when data is updated

- scripts/update.mjs
- scripts/utilities.mjs
Ref: https://github.com/sindresorhus/globals/pull/231#issuecomment-1954739725
> Update update script to be incremental

- data/chai.mjs
- globals.json
> Added chai.js globals

- .github/workflows/es-yearly-globals.yml
- scripts/create-yearly-es-globals.mjs
Let's be the laziest people in the world.
> Add automated job to create es yearly globals

- .github/workflows/update.yml
`BarcodeDetector`([issue](https://github.com/sindresorhus/globals/issues/204)) is only available on macOS, this will fix it.
[CI job on my fork](https://github.com/fisker/globals/actions/runs/11073115720)
[Result PR on my fork](https://github.com/fisker/globals/pull/4/files)
> Collect globals on all platforms

- .github/workflows/es-yearly-globals.yml
- .github/workflows/update.yml
https://github.com/sindresorhus/get-east-asian-width/pull/8
> Add `permissions` for automated job

- .github/workflows/update.yml
It currently fails https://github.com/sindresorhus/globals/actions/runs/13082902957/job/36509923924
Log on my fork https://github.com/fisker/globals/actions/runs/13279996940/job/37076439199
> Fix "Update" job

- data/vitest.mjs
- globals.json
- package.json
Fixes: https://github.com/sindresorhus/globals/issues/278
> Regenerate vitest globals

- .github/workflows/update.yml
- package.json
- patches/@puppeteer+browsers+2.10.3.patch
- scripts/get-browser-globals.mjs
Tested on my fork https://github.com/puppeteer/puppeteer/issues/13853
The fix is hacky, we'll revisit in future.
> Fix update script

- .github/workflows/update.yml
- package.json
- scripts/browser/assets/audio-worklet.mjs
- scripts/browser/assets/main.mjs
- scripts/browser/assets/service-worker.mjs
- scripts/browser/assets/web-worker.mjs
- scripts/browser/index.html
- scripts/browser/readme.md
- scripts/browser/server.mjs
- scripts/browser/start.mjs
- scripts/get-browser-globals.mjs
- scripts/utilities.mjs
Move logic into `scripts/browser/`, can run directly in browser, easier to debug.
> Rewrite scripts to get globals in browser
