globals.json

I scraped them from [these docs](http://docs.mongodb.org/manual/reference/method/) and removed the ones marked as "internal use only". They are all writable in the following sense:
```javascript
ObjectId = 1;
Objectid === 1; // true
```
I'm not sure whether this is what the boolean flag is supposed to mean.

Add support for Mongo shell

---

globals.json

While it'll be deprecated along with `GLOBAL` [eventually](https://github.com/nodejs/io.js/pull/1838), it should be here for completeness sake.

Add undocumented 'root' global for node

---

globals.json

See https://github.com/sindresorhus/globals/issues/35 for discussion on this. The prime motivation is to get these two recognized by eslint, which as it stands doesn't import the nonstandard category into any environment.

Remove nonstandard category

---

globals.json

Even if it is not listed in the documentation under [Globally injected variables](http://facebook.github.io/jest/docs/api.html#globally-injected-variables), `expect` is indeed injected globally, like jasmine does. You can see its usage in the [Getting started](http://facebook.github.io/jest/docs/getting-started.html#content) example.

Define "expect" in jest environment

---

globals.json

The `exports` variable should be assignable for CommonJS as well, am I wrong?

Make exports: true for commonjs, just like it is for Node

---

globals.json

Adds a new environment, `universal` which only has the intersection of `node` and `browser` for "isomorphic" JavaScript.

Add `shared-node-browser` environment

---

globals.json

This is the [Userscript API](http://wiki.greasespot.net/Greasemonkey_Manual:API) available in [Greasemonkey](https://addons.mozilla.org/en-US/firefox/addon/greasemonkey/), [Tampermonkey](https://chrome.google.com/webstore/detail/tampermonkey/dhdgffkkebhmkfjojejmpbldmpobfkfo) and compatible engines.

add 'greasemonkey' environment

---

globals.json

This completes the list of test helpers that people may be accessing via globals. There are other test helpers listed on http://emberjs.com/api/classes/Ember.Test.html but they should not be accessed via globals.

Add findWithAssert and pauseTest to embertest

---

globals.json

Following the naming convention from #43, this adds the globals found in Atom package tests (see https://github.com/atom/atom/blob/329d7f4/spec/spec-helper.coffee).

add 'atomtest' environment

---

globals.json

This adds `Blob` to the worker environment, since that API is available there.

Blob is available in worker context

---

globals.json

All the CommonJS wrappers (browserify, webpack, etc.) include `global` in their environments.
Related: https://github.com/eslint/eslint/issues/4728

Add global to commonjs

---

globals.json

I guess these have been forgotten.

Fix: remove `Float*Array` from `es5`

---

globals.json

The current version of Node.js (5.10.0) and versions going back at least
to 0.12.7 have the `Intl` global.

add `Intl` for nodejs

---

globals.json

This adds the `fit` variable to Jest's list of global variables, which is currently missing but exported by Jest.
http://facebook.github.io/jest/docs/api.html#globally-injected-variables

Add fit to Jest globals

---

globals.json

`run()` is available globally when [`delay` mode](https://mochajs.org#delayed-root-suite) is used

add mocha's global run() function

---

globals.json

It was added for Custom Elements v1.  At least Chrome already implemented this.
ref: https://developers.google.com/web/fundamentals/getting-started/primers/customelements

Add `customElements` to browser env

---

globals.json

It's a WebRTC feature. We can record audio and video right in browser.
https://developer.mozilla.org/en-US/docs/Web/API/MediaRecorder

Add MediaRecorder

---

globals.json

Added in https://github.com/emberjs/ember.js/pull/13663, and enabled in https://github.com/emberjs/ember.js/pull/14981.
This is available from Ember 2.13+.

Add `resumeTest` to `embertest`

---

globals.json

This is the counterpart of `requestIdleCallback`, which was added by #101.
https://developer.mozilla.org/en-US/docs/Web/API/Window/cancelIdleCallback
cc @amilajack

Add cancelIdleCallback to browser

---

globals.json

AbortController, AbortSignal are implemented already in Firefox + Edge, and soon in Chrome (crbug.com/750599)
I realize that this project typically only imports globals from Chrome canary and defines those as the "browser environment". However, it seems that Chrome is the last browser to implement abortable fetch and not having AbortController, AbortSignal recognized as globals is causing some problems; I've implemented a polyfill for AbortController (mostly for IE 11 etc) but right now it cannot be used (without springling eslint suppressions) in projects based on "create-react-app" because CRA defined no-undef as a build error and eslint doesn't know that "AbortController" is part of the browser API. More specifically, I would like to avoid telling all users of abortcontroller-polyfill …

Add AbortController, AbortSignal in "browser" environment

---

globals.json

`BigInt` is available in Node.js 10.4.0 and Chrome 67. I think it's rather unlikely that the current stage 3 proposal will not be made a standard, so I added it to `builtin`.

Add BigInt to builtin

---

globals.json

`Y` is not a global variable it's just a conventional name for the reference of the YUI instance.
YUI 3: https://yuilibrary.com/yui/docs/api/classes/YUI.html#property_YUI_config
YUI 2: http://yui.github.io/yui2/docs/yui_2.9.0_full/yahoo/#config
eslint/eslint#10775

fix yui global variables

---

globals.json

[`WorkerGlobalScope`](https://developer.mozilla.org/en-US/docs/Web/API/WorkerGlobalScope) is defined in Web Workers, it's exists [basically everywhere](https://developer.mozilla.org/en-US/docs/Web/API/WorkerGlobalScope#Browser_compatibility) and it's [useful for environment detection](https://stackoverflow.com/a/18002694/2048874). This PR fixes #127.

Add `WorkerGlobalScope` to `worker` environment

---

globals.json

The "location" property on a window is writeable not just read-only, so I think we should update the globals list to handle this.
See the discussion in the first two comments on this bug for details: https://bugzilla.mozilla.org/show_bug.cgi?id=1509270

Change `location` in the browser environment to be a read-write global, rather than read-only

---

globals.json

Resolves sindresorhus/globals#146

Add cloneInto, exportFunction and createObjectIn for greasemonkey environment

---

globals.json

It's been available since Node.js v11.0.0.
Refs: https://github.com/nodejs/node/pull/27399
It's also available in (at least) recent Chrome and Firefox but I don't know what your policy is w.r.t. to something that only a subset of browsers support.

Add `globalThis` to `builtin` environment

---

globals.json

This PR removes the `XDomainRequest` global for WSH, which is not documented in
the [JScript Reference] or [WSH Reference] and not present on Windows 7 or Windows 10 (the only versions I checked).
It also adds [`Debug`], which is provided by JScript 3 and later (released with IE 4) which WSH uses.  I confirmed it is present on Windows 7 and 10.
Thanks for considering,
Kevin
[`Debug`]: https://docs.microsoft.com/en-us/previous-versions/windows/internet-explorer/ie-developer/scripting-articles/bs12a9wf(v=vs.84)
[JScript Reference]: https://docs.microsoft.com/en-us/previous-versions/windows/internet-explorer/ie-developer/scripting-articles/yek4tbz0(v=vs.84)
[WSH Reference]: https://docs.microsoft.com/en-us/previous-versions//98591fh7%28v%3dvs.85%29

Add a global for `wsh`

---

globals.json

This PR adds two additional global functions provided by JScript in Windows Script Host and specified by Microsoft:
* [CollectGarbage] is a function provided by JScript on the global object which triggers the garbage collector.  It is required to [work around ActiveX object retention issues] in some situations.
* [RuntimeObject] is a function provided by JScript on the global object for enumerating functions and variables defined in the global scope.
I can confirm both variables are present on both Windows 7 and 10.
Thanks,
Kevin
[CollectGarbage]: https://docs.microsoft.com/en-us/openspecs/ie_standards/ms-es3ex/73a13f4c-72b3-48f3-b2f4-933084ec8716
[RuntimeObject]: https://docs.microsoft.com/en-us/openspecs/ie_standards/ms-es3ex/a17cdcdb-ef33-43e0-b269-9634e59b1a00
[work around ActiveX …

Add CollectGarbage and RuntimeObject to wsh

---

globals.json
readme.md
test.js

The `node` section mixes both globals and the arguments passed into CommonJS function bodies. This creates a new `nodeBuiltin` section that only includes the true globals. It's meant to be used  for ES modules or other code that runs outside of CommonJS wrappers.
---
_This PR was started by: [git wf pr](https://github.com/groupon/git-workflow/releases/tag/v1.0.4)_

Add true globals for Node.js

---

globals.json

The *underscore* package is not included in Meteor by default since Meteor 1.7 (https://github.com/meteor/meteor/pull/9596), so `_` is no longer in the global namespace by default. This removes `_` from the `meteor` globals group.

Remove `_` global from `meteor`

---

globals.json

Adds `AggregateError` global to `builtin` and `es2021` environments.
https://tc39.es/ecma262/#sec-aggregate-error-constructor:
> is the initial value of the "AggregateError" property of the global object.
Proposal: https://github.com/tc39/proposal-promise-any

Add `AggregateError` to `builtin` and `es2021`

---

globals.json

Introduced in NodeJS v15. See details at https://nodejs.org/docs/latest-v15.x/api/globals.html#globals_class_abortcontroller . 
See also https://developer.mozilla.org/en-US/docs/Web/API/AbortController .

Add `AbortController` to `node`

---

globals.json

https://w3c.github.io/mediacapture-main/#overconstrainederror-interface

Add `OverconstrainedError` to `browser` environment

---

globals.json

Removes a space character from the name of `AudioWorkletGlobalScope` browser global.

Remove trailing space from `AudioWorkletGlobalScope`

---

globals.json

MediaStreamConstraints is an interface used for the Media Streams API, see https://udn.realityripple.com/docs/Web/API/MediaStreamConstraints

Add MediaStreamConstraints interface to browsers environment

---

globals.json

Hi :)
The `ToggleEvent` is a new event that is called when a `popover` html element changes visibility.
I am trying to use it in a new project, and Eslint is not happy about it.
Reference: https://developer.mozilla.org/en-US/docs/Web/API/ToggleEvent

Add `ToggleEvent`
